<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.hammer</groupId>
    <artifactId>wikitext</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>wikitext</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
        <tycho-version>5.0.3</tycho-version>
        <target.classifier></target.classifier>
        <target.file>rcptarget.target</target.file>
    </properties>

    <modules>
        <module>rcptarget</module>
        <module>wikitext-sample</module>
    </modules>

    <developers>
        <developer>
            <id>chammer</id>
            <name>Carsten Hammer</name>
            <email>carsten.hammer@t-online.de</email>
        </developer>
    </developers>

    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-maven-plugin</artifactId>
                <version>${tycho-version}</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
</project>
